FIX to make GridFieldOrderableRows support polymorphic ManyManyThroughList
symbiote/silverstripe-gridfieldextensions pull request #296
Opened 2019-09-06 05:16 UTC by normann

The fix is for the issue
https://github.com/symbiote/silverstripe-gridfieldextensions/issues/295
To verify the fix, a reference of commits in core could be found:
https://github.com/silverstripe/silverstripe-framework/commit/257ff69e321e08af743de019ae338a291cb62615#diff-08f0e871daf5c0fd584acad12a119155R194

2019-12-11 02:52 UTC, michalkleiner commented
Force-pushed a version rebased on the latest 3.2 with updated Travis config to have the tests (hopefully) passing.

2020-03-02 11:00 UTC, michalkleiner commented
@dnsl48 or @Cheddam, could you guys please kindly have a look at this PR? Thanks a lot!

2020-03-02 19:14 UTC, dnsl48 commented
Yes, definitely! Thanks for the PR, will have a look later this week.

2020-05-18 01:47 UTC, dnsl48 commented
## merge checklist
 
* [x] the target branch is [correct](https://docs.silverstripe.org/en/4/contributing/code/#picking-the-right-version)
* [x] all commits are relevant (e.g. no debugging and linting)
* [x] the commit messages follow [the contribution guidelines](https://docs.silverstripe.org/en/4/contributing/code/#commit-messages)
* [x] the patch follows [the contribution guidelines](https://docs.silverstripe.org/en/4/contributing/code/)
* [ ] new features are covered with tests (back-end with unit tests, front-end with Behat)
* [x] the relevant CMS documentation is updated; changelog for impactful changes
* [x] CI is green
* [ ] at least one peer reviewer approved; no changes requested

2020-05-18 01:55 UTC, dnsl48 requested changes
Hi @michalkleiner, @normann 
Thank you for the PR and sorry it took that long to review it.
The patch is good, and thank you for spending time to contribute this feature with that complexity!

Apart from small refactoring that I mentioned in the review feedback, we also need to add tests to cover polymorphic m2ms.
I've actually patched those things locally and wrote some tests for you, but I don't have access to push to your branch. If you could give me access to your repo, I could push my patches and we could merge this PR.
Another option if you pull my changes yourself. I'm leaving them in this branch - https://github.com/creative-commoners/silverstripe-gridfieldextensions/tree/manymanythrough_ploymorphic_support

Thank you for your effort again.
Cheers

2020-05-18 01:55 UTC, dnsl48 commented on src/GridFieldOrderableRows.php
> +    protected function getManyManyInspectorForeignKeyMethod($inspector)
This method should be `private`. We cannot add new APIs in a patch release.

2020-05-18 01:55 UTC, dnsl48 commented on src/GridFieldOrderableRows.php
> +            return 'getForeignIDKey';
Any reason we should return a string here instead of calling the method and returning its result?

2020-05-18 01:55 UTC, dnsl48 commented on src/GridFieldOrderableRows.php
> +        $foreignKeyMethod = $this->getManyManyInspectorForeignKeyMethod($manipulator);
if the method returned the method invocation result, we wouldn't have to introduce this new variable here

2020-05-18 02:10 UTC, michalkleiner commented
Thanks for the review and the updates @dnsl48, I've allowed temporary write access to our repo for you (an invite should be waiting for you). Cheers!

2020-05-18 03:34 UTC, dnsl48 commented
Since we're making it for a patch release (3.2.x), we cannot change the Travis CI matrix. That one includes the old versions of the framework that don't support polymorphic m2ms. This PR does not break any BC, but the tests are breaking the build. We'll have to skip those tests for now and uncomment them in the later minor release (3.3.0).

Here are the green tests running on the later framework - https://travis-ci.org/github/creative-commoners/silverstripe-gridfieldextensions/builds/688214155

2020-05-18 03:38 UTC, merged

2020-05-18 03:38 UTC, dnsl48 commented
Thank you for the contribution!
Should be released with `3.2.3`