Feature/republish live records 3
symbiote/silverstripe-gridfieldextensions pull request #334
Opened 2022-02-17 00:26 UTC by josephlewisnz

Added the ability to autopublish items that are already live 
Same request  #289  for 3 Branch

2022-02-17 09:57 UTC, dhensby requested changes
This looks good, thanks.

It would be great to have a test to cover this functionality too

2022-02-17 09:57 UTC, dhensby commented on src/GridFieldOrderableRows.php
> +     * @param boolean $republishLiveRecords
This phpdoc is for a parameter that doesn't exist.

2022-02-17 19:41 UTC, josephlewisnz commented on src/GridFieldOrderableRows.php
> +     * @param boolean $republishLiveRecords
Removed that phpdoc  param

2022-02-17 19:54 UTC, josephlewisnz commented
Regarding tests, I'm not the most experienced in that space. I could try taking a stab at it sometime late next week.

2022-11-04 14:29 UTC, purplespider commented
Can we please get this merged, @dhensby?

People have literally been trying for years to get it merged into the correct branch and a release: #289, #339, #340 😮‍💨 And for those of us pointing composer to the specific commit it's become an upgrade blocker.

Thank you! 🤞🏻

2022-11-15 23:21 UTC, dhensby commented
I don't have merge permissions on the symbiote repos anymore - I can't merge this, I'm afraid

2022-11-16 09:35 UTC, purplespider commented
@sabina-talipova Are you able to assist with merging this?

2022-11-18 02:38 UTC, merged