fix: convert default_sort array when string
symbiote/silverstripe-gridfieldextensions pull request #352
Opened 2022-12-22 19:23 UTC by gurucomkz

`GridFieldOrderableRows` cannot handle the array form of `default_sort`. This PR converts the default_sort array to a string form.

Relates to #324.
Replaces #349.

2023-03-08 02:58 UTC, GuySartorelli commented
The correct fix is #349 
Closing this PR in favor of that one which addresses the core problem.

2023-03-08 02:59 UTC, GuySartorelli commented
Oops, sorry, I read the description but didn't look at the change. This change looks correct at a glance. Will review in more depth.

2023-03-08 03:53 UTC, GuySartorelli commented
@gurucomkz You say this replaces #349... what does this do which that PR doesn't do?

2023-03-08 21:47 UTC, kourawealthtech commented
The difference of this PR was that it replaces the $defaultSort array with a string.
PR #349 introduces $defaultSortTerm which doesn't go anywhere, meaning that #349 is actually defunct.

2023-03-19 22:00 UTC, GuySartorelli requested changes
Please use a for loop instead of `array_map` as it's easier to visually parse.

At this stage whichever between this and https://github.com/symbiote/silverstripe-gridfieldextensions/pull/349 is in a working and easily visually parsable state first will probably be merged.

2023-04-05 22:33 UTC, emteknetnz commented
Closed in favor of https://github.com/symbiote/silverstripe-gridfieldextensions/pull/361

2023-04-05 22:33 UTC, closed without merging