FIX Use DataList::orderBy()
symbiote/silverstripe-gridfieldextensions pull request #353
Opened 2023-01-16 22:15 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10645

2023-01-16 22:44 UTC, dhensby commented
Shouldn't there be a consistent interface across all lists?

2023-01-17 00:06 UTC, emteknetnz commented
SS_List does not specify sort() (or the new orderBy() which is DataList only) - https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/SS_List.php

We need to use DataList::orderBy() because it's specifically for using raw SQL.  DataList::sort() no longer accepts raw SQL

2023-01-17 10:39 UTC, maxime-rainville requested changes
Minimally, I would like to have a unit test to cover this scenario. 

The original error says `Uncaught InvalidArgumentException: Invalid sort column "EditableFormField"."Sort"`. Maybe, I'm being naive here, but shouldn't we be able to do something like `FooBar::get()->sort('Relation.SortField')`? Are you meant to be able to use the Dot notation in `sort`?

Side note: I'm not a big fan of how these `$sortterm`. Seems like at least part of this could made to use the regular sort.

2023-01-17 21:10 UTC, emteknetnz commented
You can still use dot notation in sort(), in this instance it would just be `->sort('Sort')`, not `->sort('EditableFormField.Sort'`, because we're in the context of an `EditableFormField`.  However in this method there's a bunch of raw SQL being written e.g. `$sortterm .= "$col $dir, ";`, `$sortterm .= ($sortterm ? ', ' : '') . $defaultSort;`, so we need to use `orderBy()` here to retain the current logic.

Have added unit test

2023-01-17 23:03 UTC, maxime-rainville commented on tests/GridFieldOrderableRowsTest.php
> +    public function provideGetManipulatedData(): array
Love the DataProvider. That's much nicer.

2023-01-17 23:06 UTC, maxime-rainville approved these changes
Can live with this. Tested that the new unit test fail without the fix.

> However in this method there's a bunch of raw SQL being written e.g. $sortterm .= "$col $dir, ";, $sortterm .= ($sortterm ? ', ' : '') . $defaultSort;

That's what I mean by this could easily be rewritten to work with sort. Maybe something like:
```php
$sortterm[$col] = $dir;
```

2023-01-18 01:00 UTC, merged

2023-01-18 01:01 UTC, emteknetnz commented
Note the `4 of 6 checks passed` was github actions being weird, the 'context' and 'generate matrix' had duplicate jobs created which were stuck in yellow.  All the actual jobs were green.